---
- name: Start and enable httpd service
  service:
    name: httpd
    enabled: true
    state: started

- name: create a new directory for the Ansible demo webiste files
  ansible.builtin.file: 
    path: "{{ web_dir }}"
    state: directory

- name: copying the index html template 
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_dir }}/index.html"

- name: Allow traffic for https service
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
